### ISSUE TITLE
Manual download error should not be reported if already done so

### ISSUE THREAD

**Issue by abudden** [markdoliner/flickrmirrorer#11]
I ran `flickr_mirrorer.py` and it said:

    Error: Some files failed to download:
    Manual download required: https://www.flickr.com/video_download.gne?id=27918881572

So I went to that link, downloaded that file and placed it into the `photostream` folder with all the other files that had been downloaded successfully by the script.

I then ran the script again to check that the error had gone away but it was still there and the error code was `1` (which makes the script I use with cron generate some output to the terminal rather than the log file and hence I get an email telling me of a problem).

Am I doing something wrong?

**Comment by markdoliner** [comment]
Hi, abudden! Sorry for the delayed response. I don't think you were doing anything wrong. I've also been getting those same errors when downloading videos. It started happening earlier this year and I wasn't able to figure out a workaround. From what I could tell it was no longer possible to download the original video file using the Flickr API. I'll try to find time to look at it again within the next 7 days.

**Comment by markdoliner** [comment]
Oh, and I think it warns about not being able to download the file even though it already exists because of a quirk in how videos are mirrored. The script makes an HTTP HEAD request to check the file extension for the video. I think this is the request that's failing, and I think it happens _before_ the check for whether the file already exists (because it currently needs to know the file extension of the local file). I might take a stab at improving this, too.

**Comment by ciprian-radu** [comment]
@abudden Flickr API has some limitations when it comes to videos. I did some changes in that area of the code, maybe they will help in your case too.

@markdoliner Those changes for videos processing are part of my pull request.

**Comment by markdoliner** [comment]
I merged ciprian-radu's changes in, so this problem should be fixed now: The script no longer tells you to download videos if they have already been downloaded.

Feel free to download a new version and try it out.

**Comment by abudden** [comment]
I've downloaded the latest version from github and tried it.  With the new version, it states this: 

    The Flickr API does not allow downloading original video files.
    Please save the files listed below to the photostream directory.
    Note: You must be logged into your Flickr account in order to download your full resolution videos!
      Manual download required (video may have changed): https://www.flickr.com/video_download.gne?id=27918881572
    Fetching 27918881572.mp4

and then if run again says the same thing without the "Fetching..." line.  Repeated runs just alternate between the two versions of the message.

So this doesn't seem to have fixed the issue.

**Comment by markdoliner** [comment]
abudden: Whoops, you're right. I broke that. I just committed another little change that hopefully fixes it. Sorry for the inconvenience.

**Comment by abudden** [comment]
@markdoliner Thanks - the new version works great.
