### ISSUE TITLE
Warn before deleting anything!

### ISSUE THREAD

**Issue by felipesanches** [markdoliner/flickrmirrorer#12]
I have just checked out the code and after a quick glance I noticed that it deletes "unknown files on root dir". That sounds pretty scary. And it seems that the script is equipped and ready to promptly delete all files in the backup folder without warning the user first.

It would be better/safer to ask first.

**Comment by ciprian-radu** [comment]
I forked the project and developed it towards what I needed. You will find the delete disabled there by default.

**Comment by felipesanches** [comment]
@ciprian-radu nice! Would be good to merge it back into the upstream project, ideally.

**Comment by felipesanches** [comment]
possibly adding a command-line argument to enable/disable the deletion behaviour.

**Comment by emijrp** [comment]
Yes please, fix that. I don't like scripts that delete stuff.

**Comment by markdoliner** [comment]
Hi! Great idea. I'll work on merging ciprian-radu's changes back into the upstream project. I'll try to have that finished within the next 7 days (I want to review/sanity check first, and I won't have much available time over the next few days).

**Comment by ciprian-radu** [comment]
@markdoliner I have created a pull request with my changes. Please consider it for merging.

**Comment by markdoliner** [comment]
I merged ciprian-radu's changes into master. Unknown files are no longer deleted by default. Feel free to download the new version and try it out. To get the old behavior, run the script with `--delete-unknown`.

So there is now a master on/off switch to control deleting behavior. There's no interactive "do you want to delete file XYZ?" prompt. Does that seem ok to people? We could potentially add some sort of `--delete-unknown=ask` option if people think it would be useful.

**Comment by felipesanches** [comment]
I think there's no need for an interactive mode. The flag you added solves the issue. Whoever wants deletion of files will have to ask for it explicitly on the command line, so that's safe now :-D
