### ISSUE TITLE
Nested collections

### ISSUE THREAD

**Issue by jpffitch** [markdoliner/flickrmirrorer#18]
What does this mean?

> python3 flickrmirrorer.py --ignore-videos ~/aff/Bulkr
Updating collection Brabant & Lorraine 2012
Traceback (most recent call last):
  File "flickrmirrorer.py", line 812, in <module>
    main()
  File "flickrmirrorer.py", line 807, in main
    mirrorer.run()
  File "flickrmirrorer.py", line 195, in run
    self._run_helper()
  File "flickrmirrorer.py", line 242, in _run_helper
    self._mirror_collections()
  File "flickrmirrorer.py", line 544, in _mirror_collections
    collection_dirs |= self._mirror_collection(collection)
  File "flickrmirrorer.py", line 564, in _mirror_collection
    for album in collection['set']:
KeyError: 'set'

**Comment by jpffitch** [comment]
This seems repeatable.  I have only passing knowledge of python but the line in question is
``
for album in collection['set']:
``
and the word set seems to be in error

**Comment by jpffitch** [comment]
Still looking to fix this. I notice that the collection in question has three collections in it, so there is a second level of <collection>...</collection>  and as far as I read python there is no provision for this.  I shortened the text but the structure is clear.  Perhaps if there is nor set field it should recurse on _mirror_collection

`   <collection id="277277-72157630541724802" title="Brabant & Lorraine 2012" description="In June 2012 we, ..." iconlarge="..." iconsmall="...">`
`      <collection id="277277-72157630541843666" title="Lorraine 2012 - town, ..." description="After attending ...." iconlarge="..." iconsmall="...">`
`        <set id="72157630711037912" title="Lorraine - in town - on the road" description="" />`
`        <set id="72157630455125898" title="Lorraine, the countryside" description="" />`
`        <set id="72157630600499222" title="Lorraine - Hotel du Lac de Madine" description="" />`
`      </collection>`
`      <collection id="277277-72157630958099804" title="Lorraine - perenniel battlefield" description="Having selected ..." iconlarge="" iconsmall="h">`
`        <set id="72157630958295674" title="Hattonchatel" description="A town in Lorraine..." />`
`        <set id="72157630967850852" title="Saint-Mihiel" description="" />`
`        <set id="72157630957885204" title="Alain-Fournier ~ battlefield achaeology" description="As a venture ..." />`
`        <set id="72157631045688770" title="Montsec American Monument " description="<i>This majestic ...</i>" />`
`        <set id="72157630967888310" title="Lorraine - impossible not to mention the war " description="A set for ..." />`
`      </collection>`
`      <collection id="277277-72157630541743136" title="Wedding in Brabant" description="...." iconlarge="..." iconsmall="...">`
`        <set id="72157630541788924" title="Kapellerput" description="A conference ..." />`
`        <set id="72157630356459918" title="Wedding Day in Brabant" description="" />`
`        <set id="72157630346278600" title="For Angela" description="I hope Angela ..." />`
`      </collection>`
`    </collection>`

**Comment by jpffitch** [comment]
This patch at least stops the crash and gives a warning

```diff --git a/flickrmirrorer.py b/flickrmirrorer.py
index ef9aa85..ab8b649 100755
--- a/flickrmirrorer.py
+++ b/flickrmirrorer.py
@@ -560,14 +559,18 @@ class FlickrMirrorer(object):
             _ensure_dir_doesnt_exist(collection_dir)
             _ensure_dir_exists(collection_dir)
 
-            # Create symlinks for each album
-            for album in collection['set']:
+            # Create symlinks for each album; punt on nesting
+            try:
+              for album in collection['set']:
                 album_basename = self._get_album_dirname(album['id'], album['title'])
                 album_fullname = os.path.join(self.albums_dir, album_basename)
                 album_relname = os.path.relpath(album_fullname, collection_dir)
                 symlink_filename = os.path.join(collection_dir, album_basename)
                 os.symlink(album_relname, symlink_filename)
-
+            except KeyError:
+              sys.stderr.write('Nested collections not handled in %s' % collection['title'])
+              #for subcol in collection['collection']:
+              #  collection_dirs |= self._mirror_collection(subcol)
             # Write metadata
             self._write_json_if_different(metadata_filename, collection)
 
```

**Comment by jpffitch** [comment]
Sorry; cannot work out how to do a pull request

**Comment by markdoliner** [comment]
@jpffitch Thanks for filing this issue! I didn't even know nested collections were a thing. I just pushed a small change that should make this work correctly. Thanks again, and sorry it too me so longer to respond!
