### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by RobOo-Github** [markdoliner/flickrmirrorer#24]
flickrmirrorer-master/flickrmirrorer.py:48: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources

It's no more than a warning, but still: how can I fix this?

**Comment by markdoliner** [comment]
Hi, @RobOo-Github. Thanks for bringing this up. The script was using the `pkg_resources` API for something that wasn't very important so I removed it just now. If you pull in the updated code the warning should be gone.

**Comment by RobOo-Github** [comment]
Many thanks, appreciated! Have a great 2024!
