### ISSUE TITLE
Only first frame of videos mirrored

### ISSUE THREAD

**Issue by walles** [markdoliner/flickrmirrorer#5]
Try this:
1. Upload a video to Flickr.
2. Mirror it using `flickrmirrorer`

Current results:
* `flickrmirrorer` downloads a JPEG containing the first frame of the video.

Expected result:
* `flickrmirrorer` should have downloaded the full video.

Regards /Johan

**Comment by walles** [comment]
Resolved by #7

**Comment by markdoliner** [comment]
Done!
