### ISSUE TITLE
Incorrect symlinks for videos

### ISSUE THREAD

**Issue by vmiklos** [markdoliner/flickrmirrorer#9]
Hi,

First, thanks for flickmirrorer. :-) It works quite nicely, etc.

One corner case I hit is that it seems there is a problem with videos when it comes to creating symlinks. E.g.

```
ls -l Not\ in\ any\ album/
```

Lists

```
26955584262.jpg -> ../photostream/26955584262.jpg
```

but there is no ` ../photostream/26955584262.jpg`, there is only `../photostream/26955584262_31e455cec8.mp4`.

Regards,

Miklos

**Comment by markdoliner** [comment]
vmiklos: Thanks for reporting that! I hadn't noticed it. I just committed a fix. I've only done a small amount of testing, so please let me know if you encounter any problems. Thanks, and sorry it took me 3 months to respond!

**Comment by vmiklos** [comment]
No problem, thanks for fixing this! And yes, after I removed the album directory (the one that contains the symlinks), it got re-created correctly.

**Comment by markdoliner** [comment]
Great, glad to hear that it worked. Sorry I forgot to mention that you'll need to delete the album directory (or add or remove a photo or video from the album on Flickr). I made another small change a day ago that makes that step unnecessary (for anyone else who may have this problem and isn't aware that deleting the old album dir would fix it).

**Comment by vmiklos** [comment]
Cool, thanks!
